server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: hotel-booking-backend

  datasource:
    url: jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require
    username: postgres.pnvvffaonordefxrywvn
    password: q1w2e3r4t5y6u7i8o9p0!@#$%^&*()
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
      data-source-properties:
        sslmode: require

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: teaching-gator-22601.upstash.io
      port: 6379
      password: AVhJAAIjcDE5M2NlZTFlNWM5YmY0OTIyYWFmYWVjNjM5ZDQwZmVkNnAxMA
      ssl: 
       enabled: true # SSL flag will work if Lettuce is used (which is default)

  cache:
    type: redis

logging:
  level:
    root: DEBUG
    org.springframework.security: DEBUG
    org.hibernate: DEBUG
    org.springframework.web: DEBUG

jwt:
  secret: "jwt_hyper_secret_key_must_not_be_shared##@#"
