spring: 
 application: 
   name: hotel-booking-backend
 cache:
    type: redis
 datasource:
    url: jdbc:postgresql://db.pnvvffaonordefxrywvn.supabase.co:5432/postgres?sslmode=require
    username: postgres
    password: q1w2e3r4t5y6u7i8o9p0!@#$%^&*()
    driver-class-name: org.postgresql.Driver
 jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect 
    hibernate: 
     ddl-auto: update
    show-sql: true
    properties:
     hibernate:
      format_sql: true

 redis:
    host: localhost          
    port: 6379 
logging:
  level:
    org.springframework.cache: DEBUG
    org.springframework.data.redis: DEBUG
# postgresql://localhost:5432/bookingdb 