spring: 
 application: 
   name: hotel-booking-backend
 datasource:
    url: jdbc:postgresql://localhost:5432/bookingdb
    username: java_backend
    password: 1234
 jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect 
    hibernate: 
     ddl-auto: update
    show-sql: true
    properties:
     hibernate:
      format_sql: true

 redis:
    host: localhost          # Redis server hostname
    port: 6379 