spring:
  security:
    user:
      name: disabled
  application:
    name: hotel-booking-backend
  cache:
    type: redis
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
      data-source-properties:
        sslmode: require

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  redis:
    host: ${REDIS_HOST}
    password: ${REDIS_PASSWORD}
    ssl: true
    port: 6379
logging:
  level:
    org.springframework.cache: DEBUG
    org.springframework.data.redis: DEBUG
jwt:
  secret: "jwt_hyper_secret_key_must_not_be_shared##@#"

